name: Frontend CI

on:
  push:
    branches: ['main']
    paths:
      - 'apps/frontend/**'
  pull_request:
    branches: ['main']
    paths:
      - 'apps/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('apps/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install
        working-directory: apps/frontend

      - name: Lint code
        run: npm run lint
        working-directory: apps/frontend

      - name: Build application
        run: npm run build
        working-directory: apps/frontend
